export const DEFAULT_FUNDING_ROUND_COLOR = "#64748B";

export const FUNDING_ROUNDS_COLORS = {
  seed: "#94A3B8",
  series_a: "#06B6D4",
  series_b: "#0EA5E9",
  series_c: "#3B82F6",
  undisclosed: "#A8A29E",
  debt_financing: "#F87171",
  series_unknown: "#FB923C",
  post_ipo_equity: "#FBBF24",
  post_ipo_debt: "#FACC15",
  grant: "#A3E635",
  equity_crowdfunding: "#4ADE80",
  pre_seed: "#34D399",
  corporate_round: "#2DD4BF",
  convertible_note: "#22D3EE",
  product_crowdfunding: "#38BDF8",
  angel: "#60A5FA",
  series_d: "#818CF8",
  private_equity: "#A78BFA",
  series_f: "#C084FC",
  series_g: "#E879F9",
  secondary_market: "#F472B6",
  series_e: "#FB7185",
  non_equity_assistance: "#F43F5E",
  series_j: "#EC4899",
  series_i: "#D946EF",
  initial_coin_offering: "#A855F7",
  series_h: "#8B5CF6",
  post_ipo_secondary: "#6366F1",
};

export const FUNDING_ROUNDS_NAMES = {
  seed: "SEED",
  series_a: "A",
  series_b: "B",
  series_c: "C",
  undisclosed: "UND",
  debt_financing: "DF",
  series_unknown: "UNK",
  post_ipo_equity: "PIE",
  post_ipo_debt: "PID",
  grant: "GRANT",
  equity_crowdfunding: "EC",
  pre_seed: "PRE",
  corporate_round: "CR",
  convertible_note: "CN",
  product_crowdfunding: "PC",
  angel: "ANGEL",
  series_d: "D",
  private_equity: "PE",
  series_f: "F",
  series_g: "G",
  secondary_market: "SM",
  series_e: "E",
  non_equity_assistance: "NEA",
  series_j: "J",
  series_i: "I",
  initial_coin_offering: "ICO",
  series_h: "H",
  post_ipo_secondary: "PIS",
};

export const TOP_COMPANIES_QUANTITY = 8;
export const RECENT_FUNDINGS_QUANTITY = 50;
export const MIN_CHARACTERS_FOR_SEARCHING = 3;
